# 🚀 Cấu hình mô hình phân cấp 2 tầng cho viLegalBert
# Phân loại văn bản pháp luật Việt Nam

# ============================================================================
# THÔNG TIN MÔ HÌNH
# ============================================================================
model_info:
  name: "Hierarchical Legal Classifier"
  type: "Multi-level Classification"
  architecture: "Two-stage hierarchical classifier"
  language: "Vietnamese"
  description: "Phân loại văn bản pháp luật theo 2 tầng: loại văn bản và domain"
  
# ============================================================================
# CẤU HÌNH KIẾN TRÚC PHÂN CẤP
# ============================================================================
architecture:
  # Tầng 1: Phân loại loại văn bản cơ bản
  level1:
    name: "Document Type Classifier"
    classes: [
      "LUẬT",
      "NGHỊ ĐỊNH", 
      "THÔNG TƯ",
      "NGHỊ QUYẾT",
      "QUYẾT ĐỊNH",
      "CHỈ THỊ",
      "PHÁP LỆNH",
      "NGHỊ QUYẾT LIÊN TỊCH",
      "THÔNG TƯ LIÊN TỊCH",
      "NGHỊ ĐỊNH LIÊN TỊCH"
    ]
    num_classes: 10
    description: "Phân loại theo loại văn bản pháp lý"
    
  # Tầng 2: Phân loại domain pháp lý
  level2:
    name: "Legal Domain Classifier"
    classes: [
      "HÌNH SỰ",
      "DÂN SỰ",
      "HÀNH CHÍNH",
      "LAO ĐỘNG",
      "THUẾ",
      "DOANH NGHIỆP",
      "ĐẤT ĐAI",
      "XÂY DỰNG",
      "GIAO THÔNG",
      "Y TẾ",
      "GIÁO DỤC",
      "TÀI CHÍNH",
      "MÔI TRƯỜNG",
      "AN NINH",
      "KHÁC"
    ]
    num_classes: 15
    description: "Phân loại theo lĩnh vực pháp lý chuyên biệt"
    
# ============================================================================
# CẤU HÌNH BACKBONE MODELS
# ============================================================================
backbone:
  # PhoBERT backbone
  phobert:
    model_name: "vinai/phobert-base"
    max_length: 512
    hidden_size: 768
    use_pooling: true
    pooling_method: "cls"  # cls, mean, max
    
  # BiLSTM backbone
  bilstm:
    hidden_size: 256
    num_layers: 2
    bidirectional: true
    dropout: 0.2
    
  # SVM backbone
  svm:
    kernel: "rbf"
    C: 1.0
    gamma: "scale"
    max_features: 10000
    ngram_range: [1, 3]
    feature_selection: true
    selection_method: "chi2"
    k_best: 5000
    
  # Ensemble approach
  ensemble:
    use_ensemble: true
    ensemble_method: "weighted_average"  # simple_average, weighted_average, voting
    weights: [0.4, 0.3, 0.3]  # [phobert_weight, bilstm_weight, svm_weight]
    
# ============================================================================
# CẤU HÌNH FEATURE EXTRACTION
# ============================================================================
feature_extraction:
  # Text preprocessing
  preprocessing:
    remove_special_chars: true
    normalize_unicode: true
    lowercase: false  # Giữ nguyên chữ hoa cho văn bản pháp lý
    remove_numbers: false
    max_length: 512
    
  # Feature engineering
  features:
    use_legal_keywords: true
    use_structure_features: true  # chapter, article, etc.
    use_length_features: true
    use_ministry_features: true
    
  # Legal domain keywords
  legal_keywords:
    enable: true
    keyword_weight: 0.3
    update_keywords: true
    
  # TF-IDF features (for SVM)
  tfidf_features:
    enable: true
    max_features: 10000
    ngram_range: [1, 3]
    min_df: 2
    max_df: 0.95
    
# ============================================================================
# CẤU HÌNH CLASSIFIER HEADS
# ============================================================================
classifiers:
  # Level 1 Classifier
  level1:
    input_size: 768  # PhoBERT hidden size
    hidden_layers: [512, 256]
    dropout: 0.2
    activation: "relu"
    batch_norm: true
    
  # Level 2 Classifier
  level2:
    input_size: 768  # PhoBERT hidden size + level1 features
    hidden_layers: [512, 256]
    dropout: 0.2
    activation: "relu"
    batch_norm: true
    
    # Conditional classification
    conditional_on_level1: true
    level1_conditioning: "embedding"  # embedding, one_hot, softmax
    
# ============================================================================
# CẤU HÌNH TRAINING PHÂN CẤP
# ============================================================================
training:
  # Training strategy
  strategy: "joint_training"  # separate, joint, curriculum
  
  # Curriculum learning
  curriculum:
    enable: false
    stages: [
      {"epochs": 5, "train_level1": true, "train_level2": false},
      {"epochs": 10, "train_level1": true, "train_level2": true}
    ]
    
  # Loss functions
  loss:
    level1_loss: "CrossEntropyLoss"
    level2_loss: "CrossEntropyLoss"
    joint_loss: "weighted_sum"
    loss_weights: [0.4, 0.6]  # [level1_weight, level2_weight]
    
  # Metrics
  metrics:
    level1: ["accuracy", "precision", "recall", "f1"]
    level2: ["accuracy", "precision", "recall", "f1"]
    joint: ["hierarchical_accuracy", "hierarchical_f1"]
    
# ============================================================================
# CẤU HÌNH EVALUATION PHÂN CẤP
# ============================================================================
evaluation:
  # Hierarchical metrics
  hierarchical_metrics:
    enable: true
    metrics: ["hierarchical_accuracy", "hierarchical_f1", "hierarchical_precision"]
    
  # Error analysis
  error_analysis:
    enable: true
    analyze_level1_errors: true
    analyze_level2_errors: true
    analyze_hierarchical_errors: true
    
  # Confusion matrices
  confusion_matrices:
    level1: true
    level2: true
    hierarchical: true
    
# ============================================================================
# CẤU HÌNH INFERENCE
# ============================================================================
inference:
  # Prediction pipeline
  pipeline:
    enable_level1: true
    enable_level2: true
    confidence_threshold: 0.7
    
  # Post-processing
  post_processing:
    enable: true
    methods: ["confidence_filtering", "hierarchical_constraints"]
    
  # Hierarchical constraints
  constraints:
    enable: true
    rules: [
      "level2_prediction_depends_on_level1",
      "domain_specific_constraints"
    ]
    
# ============================================================================
# CẤU HÌNH DEPLOYMENT
# ============================================================================
deployment:
  # Model serving
  serving:
    framework: "torchserve"  # torchserve, triton, custom
    batch_size: 1
    max_batch_delay: 100
    
  # API endpoints
  api:
    level1_endpoint: "/predict/level1"
    level2_endpoint: "/predict/level2"
    hierarchical_endpoint: "/predict/hierarchical"
    
  # Monitoring
  monitoring:
    enable: true
    metrics: ["latency", "throughput", "accuracy", "error_rate"] 